CREATE TABLE IF NOT EXISTS threads (
  thread_id SERIAL PRIMARY KEY NOT NULL,
  title TEXT NOT NULL UNIQUE,
  about TEXT NOT NULL,
  public BOOLEAN NOT NULL DEFAULT TRUE,
  admin_ids INTEGER[] NOT NULL
);